# Generated by Django 3.2.18 on 2023-05-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('appetizer', 'Appetizer'), ('main course', 'Main course'), ('dessert', 'Dessert'), ('side dish', 'Side dish'), ('beverage', 'Beverage'), ('bread', 'Bread'), ('snack', 'Snack'), ('vegetarian', 'Vegetarian'), ('condiments', 'Condiments'), ('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='', max_length=25),
        ),
    ]
